version: "3.8"

services:
    vue-app:
        image: romashovzimadmitry/image-anki-node
        container_name: vue-app
        env_file:
            - .env
        ports:
          - "5173:5173"
        networks:
          - vue-app-network
        depends_on:
            - vue-app-nginx
        command: "npm run dev -- --host 0.0.0.0 --port 5173"

    vue-app-nginx:
        image: romashovzimadmitry/image-anki-nginx
        env_file:
          - .env
        ports:
          - "443:443"
        networks:
          - vue-app-network
        volumes:
            - .:/app
            - ./Docker/Nginx/templates/:/etc/nginx/templates
            - ${SSL_CERTIFICATE}:/etc/nginx/certs/cert.pem:ro
            - ${SSL_CERTIFICATE_KEY}:/etc/nginx/certs/key.pem:ro

networks:
  vue-app-network:
