version: "3.8"

services:
    vue-app:
        container_name: vue-app
        env_file:
            - .env
        ports:
          - "5173:5173"
        build:
            context: .
            dockerfile: ./Docker/Node/Dockerfile
        networks:
          - vue-app-network
        depends_on:
            - vue-app-nginx
        command: "npm run dev -- --host 0.0.0.0 --port 5173"

    vue-app-nginx:
        env_file:
          - .env
        build: 
            context: .
            dockerfile: ./Docker/Nginx/Dockerfile
        ports:
          - "80:80"
          - "443:443"
        networks:
          - vue-app-network
        volumes:
            - .:/app
            - ${SSL_CERTIFICATE}:/etc/nginx/certs/cert.pem:ro
            - ${SSL_CERTIFICATE_KEY}:/etc/nginx/certs/key.pem:ro
            # https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-
#            - .env:/etc/nginx/templates

        # https://serverfault.com/a/755541
#        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
networks:
  vue-app-network:


